namespace WinForms
{
    partial class CrearPersonaForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TextBox txtNombreCompleto;
        private System.Windows.Forms.TextBox txtDni;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.TextBox txtTelefono;
        private System.Windows.Forms.TextBox txtDireccion;
        private System.Windows.Forms.ComboBox cmbProvincia;
        private System.Windows.Forms.Label lblProvincia;
        private System.Windows.Forms.ComboBox cmbLocalidad;
        private System.Windows.Forms.ComboBox cmbRol;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Button btnCancelar;
        private System.Windows.Forms.Label lblNombreCompleto;
        private System.Windows.Forms.Label lblDni;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.Label lblTelefono;
        private System.Windows.Forms.Label lblDireccion;
        private System.Windows.Forms.Label lblLocalidad;
        private System.Windows.Forms.Label lblRol;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            txtNombreCompleto = new TextBox();
            txtDni = new TextBox();
            txtEmail = new TextBox();
            txtPassword = new TextBox();
            txtTelefono = new TextBox();
            txtDireccion = new TextBox();
            cmbProvincia = new ComboBox();
            lblProvincia = new Label();
            cmbLocalidad = new ComboBox();
            cmbRol = new ComboBox();
            btnGuardar = new Button();
            btnCancelar = new Button();
            lblNombreCompleto = new Label();
            lblDni = new Label();
            lblEmail = new Label();
            lblPassword = new Label();
            lblTelefono = new Label();
            lblDireccion = new Label();
            lblLocalidad = new Label();
            lblRol = new Label();
            SuspendLayout();
            txtNombreCompleto.Location = new Point(30, 45);
            txtNombreCompleto.Name = "txtNombreCompleto";
            txtNombreCompleto.Size = new Size(240, 25);
            txtNombreCompleto.TabIndex = 0;
            txtDni.Location = new Point(30, 113);
            txtDni.Name = "txtDni";
            txtDni.Size = new Size(240, 25);
            txtDni.TabIndex = 1;
            txtEmail.Location = new Point(30, 181);
            txtEmail.Name = "txtEmail";
            txtEmail.Size = new Size(240, 25);
            txtEmail.TabIndex = 2;
            txtPassword.Location = new Point(30, 249);
            txtPassword.Name = "txtPassword";
            txtPassword.PasswordChar = '*';
            txtPassword.Size = new Size(240, 25);
            txtPassword.TabIndex = 3;
            txtTelefono.Location = new Point(30, 317);
            txtTelefono.Name = "txtTelefono";
            txtTelefono.Size = new Size(240, 25);
            txtTelefono.TabIndex = 4;
            txtDireccion.Location = new Point(30, 385);
            txtDireccion.Name = "txtDireccion";
            txtDireccion.Size = new Size(240, 25);
            txtDireccion.TabIndex = 5;
            cmbProvincia.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbProvincia.FormattingEnabled = true;
            cmbProvincia.Location = new Point(30, 453);
            cmbProvincia.Name = "cmbProvincia";
            cmbProvincia.Size = new Size(240, 28);
            cmbProvincia.TabIndex = 6;
            cmbProvincia.SelectedIndexChanged += cmbProvincia_SelectedIndexChanged;
            lblProvincia.AutoSize = true;
            lblProvincia.Location = new Point(30, 431);
            lblProvincia.Name = "lblProvincia";
            lblProvincia.Size = new Size(82, 20);
            lblProvincia.TabIndex = 6;
            lblProvincia.Text = "Provincia:";
            cmbLocalidad.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbLocalidad.FormattingEnabled = true;
            cmbLocalidad.Location = new Point(30, 521);
            cmbLocalidad.Name = "cmbLocalidad";
            cmbLocalidad.Size = new Size(240, 28);
            cmbLocalidad.TabIndex = 7;
            cmbRol.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbRol.FormattingEnabled = true;
            cmbRol.Location = new Point(30, 589);
            cmbRol.Name = "cmbRol";
            cmbRol.Size = new Size(240, 28);
            cmbRol.TabIndex = 8;
            btnGuardar.Location = new Point(170, 646);
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Size = new Size(100, 34);
            btnGuardar.TabIndex = 9;
            btnGuardar.Text = "Guardar";
            btnGuardar.UseVisualStyleBackColor = true;
            btnGuardar.Click += btnGuardar_Click;
            btnCancelar.Location = new Point(30, 646);
            btnCancelar.Name = "btnCancelar";
            btnCancelar.Size = new Size(100, 34);
            btnCancelar.TabIndex = 10;
            btnCancelar.Text = "Cancelar";
            btnCancelar.UseVisualStyleBackColor = true;
            btnCancelar.Click += btnCancelar_Click;
            lblNombreCompleto.AutoSize = true;
            lblNombreCompleto.Location = new Point(30, 23);
            lblNombreCompleto.Name = "lblNombreCompleto";
            lblNombreCompleto.Size = new Size(149, 20);
            lblNombreCompleto.TabIndex = 0;
            lblNombreCompleto.Text = "Nombre Completo:";
            lblDni.AutoSize = true;
            lblDni.Location = new Point(30, 91);
            lblDni.Name = "lblDni";
            lblDni.Size = new Size(40, 20);
            lblDni.TabIndex = 1;
            lblDni.Text = "DNI:";
            lblEmail.AutoSize = true;
            lblEmail.Location = new Point(30, 159);
            lblEmail.Name = "lblEmail";
            lblEmail.Size = new Size(50, 20);
            lblEmail.TabIndex = 2;
            lblEmail.Text = "Email:";
            lblPassword.AutoSize = true;
            lblPassword.Location = new Point(30, 227);
            lblPassword.Name = "lblPassword";
            lblPassword.Size = new Size(99, 20);
            lblPassword.TabIndex = 3;
            lblPassword.Text = "Contraseña:";
            lblTelefono.AutoSize = true;
            lblTelefono.Location = new Point(30, 295);
            lblTelefono.Name = "lblTelefono";
            lblTelefono.Size = new Size(75, 20);
            lblTelefono.TabIndex = 4;
            lblTelefono.Text = "Teléfono:";
            lblDireccion.AutoSize = true;
            lblDireccion.Location = new Point(30, 363);
            lblDireccion.Name = "lblDireccion";
            lblDireccion.Size = new Size(84, 20);
            lblDireccion.TabIndex = 5;
            lblDireccion.Text = "Dirección:";
            lblLocalidad.AutoSize = true;
            lblLocalidad.Location = new Point(30, 499);
            lblLocalidad.Name = "lblLocalidad";
            lblLocalidad.Size = new Size(86, 20);
            lblLocalidad.TabIndex = 7;
            lblLocalidad.Text = "Localidad:";
            lblRol.AutoSize = true;
            lblRol.Location = new Point(30, 567);
            lblRol.Name = "lblRol";
            lblRol.Size = new Size(35, 20);
            lblRol.TabIndex = 8;
            lblRol.Text = "Rol:";
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(304, 704);
            Controls.Add(lblNombreCompleto);
            Controls.Add(txtNombreCompleto);
            Controls.Add(lblDni);
            Controls.Add(txtDni);
            Controls.Add(lblEmail);
            Controls.Add(txtEmail);
            Controls.Add(lblPassword);
            Controls.Add(txtPassword);
            Controls.Add(lblTelefono);
            Controls.Add(txtTelefono);
            Controls.Add(lblDireccion);
            Controls.Add(txtDireccion);
            Controls.Add(lblProvincia);
            Controls.Add(cmbProvincia);
            Controls.Add(lblLocalidad);
            Controls.Add(cmbLocalidad);
            Controls.Add(lblRol);
            Controls.Add(cmbRol);
            Controls.Add(btnGuardar);
            Controls.Add(btnCancelar);
            Name = "CrearPersonaForm";
            Text = "Crear Persona";
            Load += CrearPersonaForm_Load;
            ResumeLayout(false);
            PerformLayout();
        }
    }
}

