namespace WinForms
{
    partial class EditarPersonaForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtTelefono;
        private System.Windows.Forms.TextBox txtDireccion;
        private System.Windows.Forms.ComboBox cmbProvincia;
        private System.Windows.Forms.Label lblProvincia;
        private System.Windows.Forms.ComboBox cmbLocalidad;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Button btnCancelar;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.Label lblTelefono;
        private System.Windows.Forms.Label lblDireccion;
        private System.Windows.Forms.Label lblLocalidad;
        private System.Windows.Forms.Label lblId;
        private System.Windows.Forms.TextBox txtId;
        private System.Windows.Forms.Label lblNombreCompleto;
        private System.Windows.Forms.TextBox txtNombreCompleto;
        private System.Windows.Forms.Label lblDni;
        private System.Windows.Forms.TextBox txtDni;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            txtEmail = new TextBox();
            txtTelefono = new TextBox();
            txtDireccion = new TextBox();
            cmbProvincia = new ComboBox();
            lblProvincia = new Label();
            cmbLocalidad = new ComboBox();
            btnGuardar = new Button();
            btnCancelar = new Button();
            lblEmail = new Label();
            lblTelefono = new Label();
            lblDireccion = new Label();
            lblLocalidad = new Label();
            lblId = new Label();
            txtId = new TextBox();
            lblNombreCompleto = new Label();
            txtNombreCompleto = new TextBox();
            lblDni = new Label();
            txtDni = new TextBox();
            SuspendLayout();
            txtEmail.Location = new Point(192, 125);
            txtEmail.Name = "txtEmail";
            txtEmail.Size = new Size(150, 25);
            txtEmail.TabIndex = 9;
            txtTelefono.Location = new Point(192, 159);
            txtTelefono.Name = "txtTelefono";
            txtTelefono.Size = new Size(150, 25);
            txtTelefono.TabIndex = 11;
            txtDireccion.Location = new Point(192, 193);
            txtDireccion.Name = "txtDireccion";
            txtDireccion.Size = new Size(150, 25);
            txtDireccion.TabIndex = 13;
            cmbProvincia.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbProvincia.FormattingEnabled = true;
            cmbProvincia.Location = new Point(192, 227);
            cmbProvincia.Name = "cmbProvincia";
            cmbProvincia.Size = new Size(150, 28);
            cmbProvincia.TabIndex = 15;
            cmbProvincia.SelectedIndexChanged += cmbProvincia_SelectedIndexChanged;
            lblProvincia.AutoSize = true;
            lblProvincia.Location = new Point(30, 227);
            lblProvincia.Name = "lblProvincia";
            lblProvincia.Size = new Size(82, 20);
            lblProvincia.TabIndex = 14;
            lblProvincia.Text = "Provincia:";
            cmbLocalidad.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbLocalidad.FormattingEnabled = true;
            cmbLocalidad.Location = new Point(192, 261);
            cmbLocalidad.Name = "cmbLocalidad";
            cmbLocalidad.Size = new Size(150, 28);
            cmbLocalidad.TabIndex = 17;
            btnGuardar.Location = new Point(221, 306);
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Size = new Size(100, 34);
            btnGuardar.TabIndex = 18;
            btnGuardar.Text = "Guardar";
            btnGuardar.UseVisualStyleBackColor = true;
            btnGuardar.Click += btnGuardar_Click;
            btnCancelar.Location = new Point(53, 306);
            btnCancelar.Name = "btnCancelar";
            btnCancelar.Size = new Size(100, 34);
            btnCancelar.TabIndex = 19;
            btnCancelar.Text = "Cancelar";
            btnCancelar.UseVisualStyleBackColor = true;
            btnCancelar.Click += btnCancelar_Click;
            lblEmail.AutoSize = true;
            lblEmail.Location = new Point(30, 125);
            lblEmail.Name = "lblEmail";
            lblEmail.Size = new Size(50, 20);
            lblEmail.TabIndex = 8;
            lblEmail.Text = "Email:";
            lblTelefono.AutoSize = true;
            lblTelefono.Location = new Point(30, 159);
            lblTelefono.Name = "lblTelefono";
            lblTelefono.Size = new Size(75, 20);
            lblTelefono.TabIndex = 10;
            lblTelefono.Text = "Teléfono:";
            lblDireccion.AutoSize = true;
            lblDireccion.Location = new Point(30, 193);
            lblDireccion.Name = "lblDireccion";
            lblDireccion.Size = new Size(84, 20);
            lblDireccion.TabIndex = 12;
            lblDireccion.Text = "Dirección:";
            lblLocalidad.AutoSize = true;
            lblLocalidad.Location = new Point(30, 261);
            lblLocalidad.Name = "lblLocalidad";
            lblLocalidad.Size = new Size(86, 20);
            lblLocalidad.TabIndex = 16;
            lblLocalidad.Text = "Localidad:";
            lblId.AutoSize = true;
            lblId.Location = new Point(30, 23);
            lblId.Name = "lblId";
            lblId.Size = new Size(29, 20);
            lblId.TabIndex = 0;
            lblId.Text = "ID:";
            txtId.Location = new Point(192, 23);
            txtId.Name = "txtId";
            txtId.Size = new Size(150, 25);
            txtId.TabIndex = 1;
            lblNombreCompleto.AutoSize = true;
            lblNombreCompleto.Location = new Point(30, 57);
            lblNombreCompleto.Name = "lblNombreCompleto";
            lblNombreCompleto.Size = new Size(149, 20);
            lblNombreCompleto.TabIndex = 2;
            lblNombreCompleto.Text = "Nombre Completo:";
            txtNombreCompleto.Location = new Point(192, 57);
            txtNombreCompleto.Name = "txtNombreCompleto";
            txtNombreCompleto.Size = new Size(150, 25);
            txtNombreCompleto.TabIndex = 3;
            lblDni.AutoSize = true;
            lblDni.Location = new Point(30, 91);
            lblDni.Name = "lblDni";
            lblDni.Size = new Size(40, 20);
            lblDni.TabIndex = 4;
            lblDni.Text = "DNI:";
            txtDni.Location = new Point(192, 91);
            txtDni.Name = "txtDni";
            txtDni.Size = new Size(150, 25);
            txtDni.TabIndex = 5;
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(393, 364);
            Controls.Add(lblId);
            Controls.Add(txtId);
            Controls.Add(lblNombreCompleto);
            Controls.Add(txtNombreCompleto);
            Controls.Add(lblDni);
            Controls.Add(txtDni);
            Controls.Add(lblEmail);
            Controls.Add(txtEmail);
            Controls.Add(lblTelefono);
            Controls.Add(txtTelefono);
            Controls.Add(lblDireccion);
            Controls.Add(txtDireccion);
            Controls.Add(lblProvincia);
            Controls.Add(cmbProvincia);
            Controls.Add(lblLocalidad);
            Controls.Add(cmbLocalidad);
            Controls.Add(btnGuardar);
            Controls.Add(btnCancelar);
            Name = "EditarPersonaForm";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Editar Persona";
            Load += EditarPersonaForm_Load;
            ResumeLayout(false);
            PerformLayout();
        }
    }
}

